# -*- coding: utf-8 -*-
"""
/***************************************************************************
 RasterQuantilizer
                                 A QGIS plugin
 This plugin takes a raster whose values span a wide range, and produces a raster with only five unique values: 1, 2, 3, 4 and 5, each with the same frequency.
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2021-04-12
        copyright            : (C) 2021 by Antonio Sobral Almeida
        email                : 66124.almeida@gmail.com
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""

__author__ = 'Antonio Sobral Almeida'
__date__ = '2021-04-12'
__copyright__ = '(C) 2021 by Antonio Sobral Almeida'


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load RasterQuantilizer class from file RasterQuantilizer.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .raster_quantilizer import RasterQuantilizerPlugin
    return RasterQuantilizerPlugin()
